services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: lizzstore
      POSTGRES_PASSWORD: lizzstore123
      POSTGRES_DB: lizzstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
